#
# ProteinAssigner_v3
#

# Path to the file(s) containing PSM
infile:
   - /path/to/infile1.tsv
   - /path/to/infile2.tsv

# Path to output file(s) containing PSM with most probable proteins
outfile:  
   - /path/to/outfile1.tsv
   - /path/to/outfile2.tsv

# Name of the column containing peptide sequence
seq_column: plain_peptide


# name of the output column with most probable accession
mpp_a: MPP_accessions

  
# name of the output column with most probable description
mpp_d: MPP_description


# regular expressions to filter in case of ties --> "/regex1/regex2/regex3/.../"
regex: /^sp/Sus scrofa/^((?!fragment).)*$/


#Sequence

# Select mode of execution: fasta/column
mode: fasta


#
# FASTA mode parameters (if fasta mode selected)
#
fasta_params:

  # Path to fasta file used to identify candidate proteins
  fasta: /path/to/fasta.fa
  
  # decoy prefix in fasta
  decoy_prefix: DECOY_

  # Convert L, I and J to the selected letter
  iso_leucine: L
    
  # name of the output column containing candidate accessions
  candidate_a: PA_accession_candidates
  
  # name of the output column containing candidate descriptions
  candidate_d: PA_description_candidates


#
# COLUMN mode parameters (if column mode selected)
#
column_params:

  # name of the input column containing candidate accessions
  candidate_a: PA_accession_candidates

  # name of the input column containing candidate descriptions
  candidate_d: PA_description_candidates

  # Character used to separate candidate proteins
  sep_char: ;


# Number of cores
n_cores: 8
