#
# ProteinAssigner_v3
#

# Path to the file(s) containing PSM
infile:
  - Path/To/File1
  - Path/To/File2

# Path to output file(s) containing PSM with most probable proteins
outfile:
  - Path/To/File1
  - Path/To/File2

# Name of the column containing peptide sequence
seq_column: Sequence

# Select mode of execution: fasta/column
mode: column


#
# FASTA mode parameters (if fasta mode selected)
#
fasta_params:

  # Path to fasta file used to identify candidate proteins
  fasta: Path/To/Fasta.fa
  
  # decoy prefix in fasta
  decoy_prefix: DECOY_

  # Convert L, I and J to the selected letter
  iso_leucine: L

  # Column names
  column_names: 

    # name of the column containing candidate descriptions
    candidate_d: PA_description_candidates

    # name of the column containing candidate accessions
    candidate_a: PA_accession_candidates

    # name of the column with most probable description
    mpp_d: MPP_description

    # name of the column with most probable accession
    mpp_a: MPP_accessions



#
# COLUMN mode parameters (if column mode selected)
#
column_params:

  # Name of the column(s) containing information of the candidate proteins
  prot_column:
    - Protein_Accessions
    - Protein_Descriptions
  
  # Name of the output column(s) with the most probable protein
  prot_column_mpp:
    - Protein_Accessions_MP
    - Protein_Descriptions_MP
  
  # Character used to separate candidate proteins
  sep_char: ;


# Number of cores
n_cores: 4
